//! Shader file format definitions and conversion utilities
//!
//! This module defines the serialization formats for shader files, including
//! the main ShaderAsset format and helper structures for format conversion.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use ui::graph::{
    BlueprintMetadata, GraphDescription, GraphViewState,
};

// ============================================================================
// Main Shader Asset Format
// ============================================================================

/// The unified shader file format containing all shader data.
/// This is the primary format used for saving and loading shader files.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShaderAsset {
    /// Format version for forward/backward compatibility
    pub format_version: u32,

    /// The main shader graph for this shader
    pub main_graph: GraphDescription,

    /// Editor state (open tabs, view positions, etc.)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub editor_state: Option<ShaderEditorState>,

    /// Metadata about the shader itself
    #[serde(default)]
    pub shader_metadata: BlueprintMetadata,
}

impl ShaderAsset {
    /// Create a new empty shader asset
    pub fn new() -> Self {
        Self {
            format_version: 1,
            main_graph: GraphDescription::new("ShaderGraph"),
            editor_state: None,
            shader_metadata: BlueprintMetadata::default(),
        }
    }

    /// Create a shader asset from components
    pub fn from_components(
        main_graph: GraphDescription,
        editor_state: Option<ShaderEditorState>,
    ) -> Self {
        Self {
            format_version: 1,
            main_graph,
            editor_state,
            shader_metadata: BlueprintMetadata::default(),
        }
    }
}

impl Default for ShaderAsset {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// Editor State
// ============================================================================

/// Editor state for restoring the exact UI configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShaderEditorState {
    /// IDs of currently open tabs (in order)
    pub open_tab_ids: Vec<String>,

    /// Index of the active tab
    pub active_tab_index: usize,

    /// View state (pan/zoom) for each graph by tab ID
    pub graph_view_states: HashMap<String, GraphViewState>,
}

impl ShaderEditorState {
    /// Create a new editor state
    pub fn new() -> Self {
        Self {
            open_tab_ids: vec!["main".to_string()],
            active_tab_index: 0,
            graph_view_states: HashMap::new(),
        }
    }

    /// Add a tab to the editor state
    pub fn add_tab(&mut self, tab_id: String) {
        if !self.open_tab_ids.contains(&tab_id) {
            self.open_tab_ids.push(tab_id);
        }
    }

    /// Set view state for a tab
    pub fn set_view_state(&mut self, tab_id: String, view_state: GraphViewState) {
        self.graph_view_states.insert(tab_id, view_state);
    }
}

impl Default for ShaderEditorState {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// Serialization Helpers
// ============================================================================

/// Generate a file header comment for shader files
pub fn generate_file_header() -> String {
    let now = chrono::Local::now();
    let version = ui::ENGINE_VERSION;

    format!(
        "// Auto Generated by the Plugin Shader Editor\n\
         // DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN\n\
         // Generated on {} - Engine version {}\n\
         //\n\
         // This file contains the COMPLETE shader graph for this material including:\n\
         //   - Main shader graph\n\
         //   - Editor state (open tabs, camera positions, etc.)\n\
         //\n\
         // You can modify the graph by opening this material in the Plugin Shader Editor.\n\
         // The graph is saved in JSON format for human readability and version control.\n\
         //\n\
         // EDITING THE JSON STRUCTURE COULD BREAK THE EDITOR\n\
         // AND PREVENT THE GUI FROM OPENING THIS MATERIAL - BE CAREFUL\n\n",
        now.format("%Y-%m-%d %H:%M:%S"),
        version
    )
}

/// Strip header comments from a file's content
pub fn strip_header_comments(content: &str) -> String {
    content
        .lines()
        .skip_while(|line| line.trim().starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Serialize a shader asset to JSON string with header
pub fn serialize_shader_with_header(asset: &ShaderAsset) -> Result<String, String> {
    let json = serde_json::to_string_pretty(asset)
        .map_err(|e| format!("Failed to serialize shader: {}", e))?;

    Ok(format!("{}{}", generate_file_header(), json))
}

/// Deserialize a shader asset from JSON string (with or without header)
pub fn deserialize_shader(content: &str) -> Result<ShaderAsset, String> {
    let json = strip_header_comments(content);

    serde_json::from_str::<ShaderAsset>(&json)
        .map_err(|e| format!("Failed to deserialize shader: {}", e))
}

// ============================================================================
// Format Version Checking
// ============================================================================

/// Check if a shader format version is supported
pub fn is_version_supported(version: u32) -> bool {
    version == 1 // Currently only version 1 is supported
}

/// Get the current shader format version
pub fn current_format_version() -> u32 {
    1
}
